name: deploy page

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Zola
        run: | 
          wget "https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz"
          sudo tar xzf ./zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Build
        run: "export CURRENT_TIME=$(date '+%d %B %Y'); ./zola build"

      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SshPrivateKey }}
          HOST_DIR: ${{ secrets.HostDir }}
          SSH_USERNAME: ${{ secrets.SshUsername }}
          HOST: ${{ secrets.Host }}
        run: |
          apt update -y && apt-get install -y --no-install-recommends rsync
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${HOST} >> ~/.ssh/known_hosts
          rsync -r --delete-after public/* "${SSH_USERNAME}@${HOST}:${HOST_DIR}"

