name: github pages

on:
  push:
    branches:
      - gh-pages
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Zola
        run: | 
          wget "https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz"
          sudo tar xzf ./zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Build
        run: "export CURRENT_TIME=$(date '+%d %B %Y'); ./zola build"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/gh-pages' }}
        with:
          name: build_artifacts
          path: public/

  deploy:
    if: ${{ github.ref == 'refs/heads/gh-pages' }}

    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifacts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: zola-build
          cname: www.arewewebyet.org
